### ISSUE TITLE
Cant find Demo in Simplicity Studio

### ISSUE THREAD

**Issue by SethLeviton** [SiliconLabs/machine_learning_applications#1]
Attempting to complete the [Simplicity Studio: Flashing the demo example](https://github.com/SiliconLabs/machine_learning_applications/tree/main/voice/sensory_wakeupword#simplicity-studio-flashing-the-demo)

But I cannot find `Machine Learning - Sensory Wakeup Word Demo` as described in step 5. 

I have completed the [Simplicity Studio: Adding an external repository](https://github.com/SiliconLabs/machine_learning_applications/tree/main/voice/sensory_wakeupword#simplicity-studio-adding-an-external-repository) with a fresh install of Gecko SDK v4.1.0. 
Is this version correct? Any ideas on why this might be happening?

Thanks,
Seth

**Comment by silabs-eirikv** [comment]
Hi @SethLeviton,

Thanks for reaching out. There's two things I can think of that might be causing the issues you're seeing:

1. GSDK extensions requires a recent Simplicity Studio version
2. There might be multiple SDKs installed in Studio, so the default version chosen in the Studio Launcher could be different from the version where the SDK extension was installed.

So,

- Could you double check that the SDK selected in the Studio Launcher (under the `Overview` tab) is the same as the SDK where you installed the extension?
- If that fails, could you try updating Simplicity Studio, installing GSDK v4.1.3, and adding `machine_learning_applications` as an SDK extension to that GSDK version?


Sorry for the late reply.
Eirik
